### ISSUE TITLE
Onset Design

### ISSUE THREAD

**Issue by amurtet** [amurtet/path#1]
Pensate sia meglio per l'onset detection utilizzare una flag in analyze, e.g. |analyze -o sound.wav< oppure creare un metodo nuovo, |onset sound.wav< ?

**Comment by grammaton** [comment]
credo che io preferirei una flag.
lo trovo un modo più ordinato e gestibile di usare le opzioni.
G.

**Comment by amurtet** [comment]
quindi |analyze -o sound1.wav sound2.wav< potrebbe andare? In questo caso entrambi i suoni verrebbero frammentati per onset. L'alternativa e' specificare la flag per ogni suono in maniera che si possano avere suoni frammentati per frame e altri per onset.

**Comment by grammaton** [comment]
Io credo che sia una scelta operativa va bene che sia applicabile all’intero processo, semplifica molto.
poi se uno vuole le cose miste si apre due oggetti. no?
