### ISSUE TITLE
gitter

### ISSUE THREAD

**Issue by grammaton** [amurtet/path#6]
posso applicare la procedura di gitter.izzazione del repositorio?

**Comment by amurtet** [comment]
se non lo fai mi offendo!

**Comment by grammaton** [comment]
@amurtet non posso farlo. può farlo solo il dio di questo luogo.

**Comment by grammaton** [comment]
@amurtet devi registrarti su gitter.im e poi creare una stanza per il tuo repo

**Comment by amurtet** [comment]
@grammaton ma non posso renderti admin in qualche modo?

**Comment by grammaton** [comment]
si, nei settings puoi aggiungere collaboratori

**Comment by amurtet** [comment]
ti ho invitato a collaborare

**Comment by grammaton** [comment]
pigro

**Comment by amurtet** [comment]
chiudo io i problemi
